version: "3" 
services:
  go-porxy-bingai:
    container_name: go-porxy-bingai
    image: nothingnessvoid/go-proxy-bingai:latest
    ports:
      - 8080:8080         # 容器端口映射到宿主机8080端口；宿主机监听端口可按需改为其它端口
    networks:
          - caddy
    restart: unless-stopped
    # environment:
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=xxx
    #   - Go_Proxy_BingAI_SOCKS_PWD=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_1=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_2=xxx
    labels:
      caddy: 域名.com # 填写你预先解析到服务器 ip 上的域名
      caddy.reverse_proxy: "{{upstreams 8080}}"
      
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 公开 Docker 的套接字文件
      - caddy_data:/data # 存储 Caddy 的持久数据
    environment:
      - CADDY_INGRESS_NETWORKS=caddy # 告诉 Caddy 它可以代理 Docker 网络中的服务
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
